---

- name: Include OS specific variables.
  include_vars: "configure-{{ ansible_os_family }}.yml"

- name: Copy {{ httpd_package_name }} vhost
  template:
    src: "nexus-vhost.conf"
    dest: "{{ httpd_config_dir }}"

- name: Copy SSL certificate file
  copy:
    src: "{{ httpd_ssl_certificate_file }}"
    dest: "{{ certificate_file_dest }}"
    mode: 600
  when: httpd_copy_ssl_files

- name: Copy SSL certificate key file
  copy:
    src: "{{ httpd_ssl_certificate_key_file }}"
    dest: "{{ certificate_key_dest }}"
    mode: 600
  when: httpd_copy_ssl_files

- name: Setsebool httpd_can_network_connect
  shell: 'setsebool -P httpd_can_network_connect on'
  when: selinux_enabled

- name: Restart {{ httpd_package_name }}
  systemd:
    state: restarted
    name: "{{ httpd_package_name }}"

- name: Waiting for {{ httpd_package_name }} to be restarted
  wait_for:
    port: 443
    delay: 5